# Generated by Django 5.0.2 on 2024-02-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='quetsion',
            new_name='question',
        ),
    ]
