# Generated by Django 5.0.2 on 2024-02-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_quetsion_poll_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Choice',
            new_name='choice',
        ),
    ]
